version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/coredns"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/distroless-cc"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/distroless-cc-debian10"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/distroless-static"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/distroless-static-debian10"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/elasticsearch-oss"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/filebeat"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/flannel"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/kibana"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/kubernetesui-dashboard"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/logstash"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/metrics-server"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/nginx-ingress-controller"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/images/pause"
    schedule:
      interval: "daily"
