name: coredns

on:
  push:
    paths:
      - 'sync.sh'
      - 'images/coredns/*'
      - '.github/workflows/coredns.yml'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: sync images
        run: /bin/bash sync.sh images/coredns
  selfhost:
    runs-on:
      - self-hosted
      - aliyun
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.MIRROR_DOCKER_USERNAME }}
          username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
      - name: sync images
        run: REGISTRY=${{ secrets.MIRROR_DOCKER_REGISTRY }} /bin/bash sync.sh images/coredns
