name: distroless-static

on:
  push:
    paths:
      - 'sync.sh'
      - 'images/distroless-static/*'
      - '.github/workflows/distroless-static.yml'

  schedule:
    - cron: '10 3 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: sync images
        run: REGISTRY=kubeimages /bin/bash sync.sh images/distroless-static
  selfhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.MIRROR_DOCKER_REGISTRY }}
          password: ${{ secrets.MIRROR_DOCKER_PASSWORD }}
          username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
      - name: sync images
        run: REGISTRY=${{ secrets.MIRROR_DOCKER_REGISTRY }}/${{ secrets.MIRROR_DOCKER_GROUP }} /bin/bash sync.sh images/distroless-static
