name: logstash

on:
  push:
    paths:
      - 'sync.sh'
      - 'images/logstash/*'
      - '.github/workflows/logstash.yml'
    branches:
      - master


jobs:
  selfhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.MIRROR_DOCKER_REGISTRY }}
          password: ${{ secrets.MIRROR_DOCKER_PASSWORD }}
          username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
      - name: sync images
        run: REGISTRY=${{ secrets.MIRROR_DOCKER_REGISTRY }}/${{ secrets.MIRROR_DOCKER_GROUP }} /bin/bash sync.sh images/logstash
