name: docker-buildx

on:
  push:
    paths:
      - 'dockerfiles/*.Dockerfile'
      - 'sync.sh'
      - 'Makefile'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: sync images
        run: make sync

      - name: Commit files
        run: |
          git config --local user.email "workflow@github.io"
          git config --local user.name "tangxin"
          git add README.md
          git commit -am "update README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}